- lib/ice_cube.rb
- lib/ice_cube/parsers/hash_parser.rb
- lib/ice_cube/parsers/ical_parser.rb
- lib/ice_cube/rule.rb
- lib/ice_cube/schedule.rb
- lib/ice_cube/time_util.rb
- lib/ice_cube/validations/lock.rb
- spec/examples/from_ical_spec.rb
- spec/examples/ice_cube_spec.rb
- spec/examples/to_ical_spec.rb
Cleanup of #226.
Squashed all commits into one, removed non-ical changes, unbroke tests, and committed. Sorry to have lost all the contributors, but it was too unwieldy to rebase. Credits to @skyporter @jgauby @btucker @spra85.
I hope this helps in getting iCal parsing finally merged.
> Issues/50 from ical, cleaned up

- README.md
While experimenting with this library with my team I ran into the inconvenience that some of the usages of Rule in the readme are namespaced to IceCube:: and some are not, so here is a PR. :space_invader:
> Adding namespacing to Rule in Readme to make it easier to run examples

- README.md
- lib/ice_cube/schedule.rb
- spec/examples/schedule_spec.rb
Adding an option on schedule methods to include occurrences whose duration intersects a time window. Issue #154
https://github.com/seejohnrun/ice_cube/issues/154
> Option to include prior occurrences with overlapping duration

- ice_cube.gemspec
Don't try to bring in new activesupport on versions of Ruby that don't
support it
> Fix tests on older rubies

- CHANGELOG.md
- lib/ice_cube/parsers/ical_parser.rb
- lib/ice_cube/rule.rb
- spec/examples/from_ical_spec.rb
- spec/examples/to_yaml_spec.rb
Also modify `Rule#from_ical` to use `Rule#from_hash` for uniformity and
centralization of parsing logic.
> Validate rule types while parsing

- config/locales/ru.yml
Improved version of #340 
Fixes a few typos and date format.
Critical fixes:
`days_of_month`: days in month -> days of month
`days_of_year`: days in year -> days of year
`on_seconds_of_minute`: fixed wrong pluralization
removed `at_seconds_of_minute`, cause it's not being used.
Month names and weeks are NOT capitalized in Russian.
**Please, don't merge #340, it has wrong translation.**
> Add Russian locale

- lib/ice_cube/schedule.rb
- spec/examples/weekly_rule_spec.rb
This PR fixes an edge case bug for the use of the spans option when the biweekly realign method comes into effect. The realign method was being called with the opening time with the duration shift, whereas it should always be using the pure opening time.
Thanks for all the work you've been doing on the gem recently! It's not gone unnoticed.
> Fixing biweekly realign when used with spans option.

- lib/ice_cube/time_util.rb
- lib/ice_cube/validations/count.rb
- lib/ice_cube/validations/day.rb
- lib/ice_cube/validations/day_of_month.rb
- lib/ice_cube/validations/day_of_year.rb
- lib/ice_cube/validations/hour_of_day.rb
- lib/ice_cube/validations/minute_of_hour.rb
- lib/ice_cube/validations/month_of_year.rb
- lib/ice_cube/validations/second_of_minute.rb
This looks good. Thanks @patrickjaberg!
> Use Integer class to avoid Fixnum deprecation warnings in ruby 2.4

- lib/ice_cube/rule.rb
- lib/ice_cube/schedule.rb
- lib/ice_cube/time_util.rb
- spec/examples/schedule_equality_spec.rb
Add `hash` and `==` methods to track in-place changes.
Fixes #310
> Schedule can be compared as a value object

- lib/ice_cube/validated_rule.rb
- spec/examples/daily_rule_spec.rb
- spec/examples/hourly_rule_spec.rb
- spec/examples/minutely_rule_spec.rb
- spec/examples/monthly_rule_spec.rb
- spec/examples/secondly_rule_spec.rb
- spec/examples/weekly_rule_spec.rb
- spec/examples/yearly_rule_spec.rb
Yesterday I meant to call `day_of_year(-1)` but wrote instead `yearly(-1)` and was rather confused when the error message `-1 is not a valid input for interval. Please pass an integer.` appeared.
This PR just updates the error message to specify that the integer must be positive.
>  clarify error message when a nonpositive integer is passed to interval method

- lib/ice_cube/rules/weekly_rule.rb
- spec/examples/weekly_rule_spec.rb
When using a non-zero (non-Sunday) week start, the rule validations need to
choose the first wday to align onto when jumping into the schedule. The first
wday needs to be based on the correct week start, since 0 (Sunday) then comes at
the end of the week and causes the next valid occurrence to be skipped.
Fixes #400
> Realign first wday validation to the selected week_start

- lib/ice_cube/rules/weekly_rule.rb
- lib/ice_cube/schedule.rb
- spec/examples/weekly_rule_spec.rb
Clamp iteration to the schedule start time so the first iteration does not
appear to be a preceding day (or possibly week).
When using the `spans: true` option, reversing over the start time to cover the
entire duration can move the opening time into a previous day/week and cause
weekly realignment to jump into the next weekly interval.
Count whole days for realigning weekly offsets to prevent rounding down to the
previous day.
Fixes #394
> Fix weekly realignment for `spans: true` option

- CHANGELOG.md
- lib/ice_cube/schedule.rb
- lib/ice_cube/time_util.rb
- spec/examples/dst_spec.rb
Simplify the method we use for calculating time changes across DST boundaries by
performing arithmetic under UTC to get "absolute" values. This is a revert of
the "unrolling in pairs" method introduced in c93fa7e for fixing #189.
The method of converting to UTC and back for doing time arithmetic only applies
when DST needs to be taken into consideration. For rules with less than daily
intervals, both hours still need to occur. This distinction was added in the
original fix.
However, the method was not correctly tested for non-ActiveSupport times (local
system TZ) and the advancing of time to the next occurrence was validating both
the last DT hour (before fall back) and first ST hour (after fall back) causing
double occurrences for the "same" hour on the clock face.
> #398 Fix double DST occurrences

- CHANGELOG.md
- lib/ice_cube/parsers/ical_parser.rb
- lib/ice_cube/time_util.rb
- spec/examples/from_ical_spec.rb
> Parse RDATE lines in iCal parser

- lib/ice_cube/schedule.rb
- lib/ice_cube/time_util.rb
> Support time.subsec across all Ruby types & ActiveSupport versions

- config/locales/fr.yml
In French, mecredi is mercredi
> Quick language correction to a day name

- README.md
I believe 0.16.3 added RDATE support ~~making ical serialization fully supported (?)~~
Update:
Looks like parsing time zone information still isn't supported at the moment. Added note about that.
Update 2:
Also added time zone parsing support in #455.
> Update README with RDATE support

- config/locales/nl.yml
Thanks for your great library.
Here are translations for Dutch, hope these can get merged!
> Add Dutch (NL) translations

- config/locales/sv.yml
> Incorrect Swedish abbreviated month for November

- lib/ice_cube/validations/hour_of_day.rb
- spec/examples/weekly_rule_spec.rb
bug described in https://github.com/seejohnrun/ice_cube/issues/451
> fix offset bug when base_interval_validation.type is not hourly

- CHANGELOG.md
- lib/ice_cube/parsers/hash_parser.rb
- lib/ice_cube/schedule.rb
- spec/examples/to_yaml_spec.rb
Fixes #518 
- Exports exrules when `to_hash` is called, regardless of gem version
- Also fixes `to_yaml` and `to_json` since they both call `to_hash`
- Removes deprecation warning on use of `exrules`
> Correctly export exrules

- CHANGELOG.md
- ice_cube.gemspec
> Update documentation links in gemspec

- CHANGELOG.md
- lib/ice_cube.rb
- lib/ice_cube/i18n.rb
- spec/examples/to_s_en_spec.rb
ice_cube would inject its locale files at the end of `I18n.load_path` due to its `IceCube::I18n` module being `autoload`ed and thereby overwrite any customisation the user may have made in other locale files earlier in the load path.
i fix this by injecting ice cube locales at gem load time so that the user has a chance to modify locale keys later.
this also eliminates a bunch of delegation having a custom I18n module; `IceCube::I18n` is just the same as ::I18n if the i18n gem is available.
resolves #489, #432, #431
> fix I18n.load_path injection
